/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    wydarzenia: Wydarzenia;
    zgloszenia: Zgloszenia;
    'zalaczniki-zgloszen': ZalacznikiZgloszen;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    wydarzenia: WydarzeniaSelect<false> | WydarzeniaSelect<true>;
    zgloszenia: ZgloszeniaSelect<false> | ZgloszeniaSelect<true>;
    'zalaczniki-zgloszen': ZalacznikiZgloszenSelect<false> | ZalacznikiZgloszenSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    ustawienia: Ustawienia;
  };
  globalsSelect: {
    ustawienia: UstawieniaSelect<false> | UstawieniaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Visible publicly only when published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wydarzenia".
 */
export interface Wydarzenia {
  id: number;
  tytul: string;
  typ: 'konferencja' | 'szkolenie' | 'superwizja' | 'cykl' | 'webinar' | 'spotkanie' | 'inne';
  /**
   * URL part; auto-generated when empty.
   */
  slug?: string | null;
  opublikowane?: boolean | null;
  liczbaZapisanych?: string | null;
  dataOd: string;
  dataDo?: string | null;
  miejsce?: string | null;
  opis: string;
  /**
   * 0 = free.
   */
  cena: number;
  dniNaPlatnosc: number;
  limitMiejsc?: number | null;
  listaRezerwowa?: boolean | null;
  /**
   * Optional time-based prices.
   */
  progiCenowe?:
    | {
        nazwa: string;
        cenaProgu: number;
        doKiedy: string;
        id?: string | null;
      }[]
    | null;
  trybZapisu: 'wydarzenie' | 'terminy';
  terminy?:
    | {
        nazwa: string;
        data: string;
        limit?: number | null;
        cenaTerminu?: number | null;
        zapisyDo?: string | null;
        id?: string | null;
      }[]
    | null;
  pola?:
    | {
        etykieta: string;
        typ: 'tekst' | 'tekstDlugi' | 'lista' | 'opcje' | 'checkbox' | 'zalacznik' | 'info';
        wymagane?: boolean | null;
        opcje?: string | null;
        id?: string | null;
      }[]
    | null;
  zbierajDaneFaktury?: boolean | null;
  instrukcjaPlatnosci?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zgloszenia".
 */
export interface Zgloszenia {
  id: number;
  opisowy?: string | null;
  imie: string;
  nazwisko: string;
  email: string;
  telefon?: string | null;
  wydarzenie: number | Wydarzenia;
  wybraneTerminy?:
    | {
        nazwa: string;
        id?: string | null;
      }[]
    | null;
  status: 'oczekuje' | 'potwierdzone' | 'rezerwowa' | 'obecny' | 'nieobecny' | 'anulowane';
  powodAnulowania?: ('rezygnacja' | 'brak-platnosci' | 'zwrot' | 'inny') | null;
  kwotaNalezna: number;
  wplacono?: number | null;
  terminPlatnosci?: string | null;
  wplaty?:
    | {
        dzien: string;
        kwota: number;
        uwagi?: string | null;
        id?: string | null;
      }[]
    | null;
  kodPlatnosci?: string | null;
  odpowiedzi?:
    | {
        pytanie?: string | null;
        odpowiedz?: string | null;
        id?: string | null;
      }[]
    | null;
  zalaczniki?: (number | ZalacznikiZgloszen)[] | null;
  chceFakture?: boolean | null;
  faktura?: {
    nazwa?: string | null;
    nip?: string | null;
    adres?: string | null;
  };
  notatka?: string | null;
  zgodaRodo?: boolean | null;
  token?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Admin-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zalaczniki-zgloszen".
 */
export interface ZalacznikiZgloszen {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  imieNazwisko?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'wydarzenia';
        value: number | Wydarzenia;
      } | null)
    | ({
        relationTo: 'zgloszenia';
        value: number | Zgloszenia;
      } | null)
    | ({
        relationTo: 'zalaczniki-zgloszen';
        value: number | ZalacznikiZgloszen;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wydarzenia_select".
 */
export interface WydarzeniaSelect<T extends boolean = true> {
  tytul?: T;
  typ?: T;
  slug?: T;
  opublikowane?: T;
  liczbaZapisanych?: T;
  dataOd?: T;
  dataDo?: T;
  miejsce?: T;
  opis?: T;
  cena?: T;
  dniNaPlatnosc?: T;
  limitMiejsc?: T;
  listaRezerwowa?: T;
  progiCenowe?:
    | T
    | {
        nazwa?: T;
        cenaProgu?: T;
        doKiedy?: T;
        id?: T;
      };
  trybZapisu?: T;
  terminy?:
    | T
    | {
        nazwa?: T;
        data?: T;
        limit?: T;
        cenaTerminu?: T;
        zapisyDo?: T;
        id?: T;
      };
  pola?:
    | T
    | {
        etykieta?: T;
        typ?: T;
        wymagane?: T;
        opcje?: T;
        id?: T;
      };
  zbierajDaneFaktury?: T;
  instrukcjaPlatnosci?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zgloszenia_select".
 */
export interface ZgloszeniaSelect<T extends boolean = true> {
  opisowy?: T;
  imie?: T;
  nazwisko?: T;
  email?: T;
  telefon?: T;
  wydarzenie?: T;
  wybraneTerminy?:
    | T
    | {
        nazwa?: T;
        id?: T;
      };
  status?: T;
  powodAnulowania?: T;
  kwotaNalezna?: T;
  wplacono?: T;
  terminPlatnosci?: T;
  wplaty?:
    | T
    | {
        dzien?: T;
        kwota?: T;
        uwagi?: T;
        id?: T;
      };
  kodPlatnosci?: T;
  odpowiedzi?:
    | T
    | {
        pytanie?: T;
        odpowiedz?: T;
        id?: T;
      };
  zalaczniki?: T;
  chceFakture?: T;
  faktura?:
    | T
    | {
        nazwa?: T;
        nip?: T;
        adres?: T;
      };
  notatka?: T;
  zgodaRodo?: T;
  token?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zalaczniki-zgloszen_select".
 */
export interface ZalacznikiZgloszenSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  imieNazwisko?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ustawienia".
 */
export interface Ustawienia {
  id: number;
  organizator: string;
  emailKontaktowy: string;
  telefon?: string | null;
  rachunek: {
    numer: string;
    odbiorca: string;
  };
  klauzulaRodo: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ustawienia_select".
 */
export interface UstawieniaSelect<T extends boolean = true> {
  organizator?: T;
  emailKontaktowy?: T;
  telefon?: T;
  rachunek?:
    | T
    | {
        numer?: T;
        odbiorca?: T;
      };
  klauzulaRodo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}